from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet

from datetime import datetime

import os


def _create_report_path(filename, output_folder):
    """Create a collision-resistant report path for an analysis."""
    os.makedirs(output_folder, exist_ok=True)
    base_name = filename.rsplit(".", 1)[0]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    report_name = f"{base_name}_{timestamp}_TruthLens_Report.pdf"
    return os.path.join(output_folder, report_name)


def generate_report(
    filename,
    analysis,
    ai_score,
    risk_level,
    reasons,
    output_folder
):
    """
    Generate a professional PDF report.
    """

    report_path = _create_report_path(filename, output_folder)

    doc = SimpleDocTemplate(report_path)

    styles = getSampleStyleSheet()

    story = []

    # ===========================
    # Title
    # ===========================

    story.append(
        Paragraph(
            "<b><font size=20>TruthLens Analysis Report</font></b>",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 20))

    # ===========================
    # Date
    # ===========================

    story.append(
        Paragraph(
            f"<b>Generated:</b> {datetime.now()}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 12))

    # ===========================
    # File Name
    # ===========================

    story.append(
        Paragraph(
            f"<b>File Name:</b> {filename}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    # ===========================
    # Statistics
    # ===========================

    story.append(
        Paragraph(
            "<b>Document Statistics</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            f"Words : {analysis['word_count']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"Characters : {analysis['character_count']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"Sentences : {analysis['sentence_count']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"Paragraphs : {analysis['paragraph_count']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"Reading Time : {analysis['reading_time']} minute(s)",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"Vocabulary Diversity : {analysis['vocabulary_diversity']}%",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    # ===========================
    # AI Score
    # ===========================

    story.append(
        Paragraph(
            "<b>AI Analysis</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            f"AI Suspicion Score : {ai_score}%",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"Risk Level : {risk_level}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    # ===========================
    # Reasons
    # ===========================

    story.append(
        Paragraph(
            "<b>Detected Indicators</b>",
            styles["Heading2"]
        )
    )

    if reasons:

        for reason in reasons:

            story.append(
                Paragraph(
                    f"• {reason}",
                    styles["Normal"]
                )
            )

    else:

        story.append(
            Paragraph(
                "No suspicious indicators detected.",
                styles["Normal"]
            )
        )

    story.append(Spacer(1, 25))

    # ===========================
    # Footer
    # ===========================

    story.append(
        Paragraph(
            "<b>Generated by TruthLens</b>",
            styles["Heading3"]
        )
    )

    doc.build(story)

    return report_path


def generate_image_report(
    filename,
    image,
    risk_level,
    output_folder
):
    """Generate a PDF report for an image authenticity analysis."""
    report_path = _create_report_path(filename, output_folder)
    doc = SimpleDocTemplate(report_path)
    styles = getSampleStyleSheet()
    story = [
        Paragraph(
            "<b><font size=20>TruthLens Image Analysis Report</font></b>",
            styles["Title"]
        ),
        Spacer(1, 20),
        Paragraph(f"<b>Generated:</b> {datetime.now()}", styles["Normal"]),
        Spacer(1, 12),
        Paragraph(f"<b>File Name:</b> {filename}", styles["Normal"]),
        Spacer(1, 20),
        Paragraph("<b>Image Details</b>", styles["Heading2"]),
        Paragraph(f"Resolution: {image['resolution']}", styles["Normal"]),
        Paragraph(f"Format: {image['format']}", styles["Normal"]),
        Paragraph(f"Color Mode: {image['color_mode']}", styles["Normal"]),
        Paragraph(f"File Size: {image['file_size']} KB", styles["Normal"]),
        Spacer(1, 20),
        Paragraph("<b>Metadata</b>", styles["Heading2"]),
        Paragraph(f"Camera Make: {image['camera_make']}", styles["Normal"]),
        Paragraph(f"Camera Model: {image['camera_model']}", styles["Normal"]),
        Paragraph(f"Capture Date: {image['capture_date']}", styles["Normal"]),
        Spacer(1, 20),
        Paragraph("<b>AI Analysis</b>", styles["Heading2"]),
        Paragraph(f"AI Suspicion Score: {image['ai_score']}%", styles["Normal"]),
        Paragraph(f"Risk Level: {risk_level}", styles["Normal"]),
        Spacer(1, 20),
        Paragraph("<b>Detected Indicators</b>", styles["Heading2"]),
    ]

    if image["reasons"]:
        for reason in image["reasons"]:
            story.append(Paragraph(f"- {reason}", styles["Normal"]))
    else:
        story.append(Paragraph("No suspicious indicators detected.", styles["Normal"]))

    story.extend([
        Spacer(1, 25),
        Paragraph("<b>Generated by TruthLens</b>", styles["Heading3"]),
    ])
    doc.build(story)
    return report_path
